In [6]:
import pandas as pd
import numpy as np

In [7]:
url = "https://raw.githubusercontent.com/AwalDinz/analisis-sentimen-wisata-banda-aceh/main/dataset/final_dataset_wisata_banda_aceh.csv"

df = pd.read_csv(url)

print("Jumlah baris :", df.shape[0])
print("Jumlah kolom :", df.shape[1])

df.head()

Jumlah baris : 2736
Jumlah kolom : 6

,title,text,stars,publishedAtDate,likesCount,platform
0,Masjid Raya Baiturrahman,Masjid raya Baiturrahman Aceh Dibangun pada ma...,5.0,12/02/2026 11:32,0,Google Maps
1,Masjid Raya Baiturrahman,Masjid penuh sejarah bagi masyarakat terutama ...,5.0,15/01/2026 08:09,0,Google Maps
2,Masjid Raya Baiturrahman,"mashaAllah diijinkan untuk berkunjung kesini, ...",5.0,21/01/2026 01:30,1,Google Maps
3,Masjid Raya Baiturrahman,"Tiada kata selain Subhanallah, ini masjid bagu...",5.0,09/11/2025 18:43,0,Google Maps
4,Masjid Raya Baiturrahman,"Setiap kali ke Aceh, wajib kesini, masjid ini ...",5.0,22/01/2026 18:04,0,Google Maps

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2736 entries, 0 to 2735
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            2736 non-null   object
 1   text             2736 non-null   object
 2   stars            2270 non-null   float64
 3   publishedAtDate  2736 non-null   object
 4   likesCount       2736 non-null   int64
 5   platform         2736 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 128.4+ KB

In [9]:
df["platform"].value_counts()

platform
Google Maps    2270
TikTok          466
Name: count, dtype: int64

In [10]:
df["title"].nunique()

30

Case Folding

In [11]:
df_casefold = df.copy()

df_casefold["text"] = df_casefold["text"].str.lower()

df_casefold[["text"]].head()

                                                text
0  masjid raya baiturrahman aceh dibangun pada ma...
1  masjid penuh sejarah bagi masyarakat terutama ...
2  mashaallah diijinkan untuk berkunjung kesini, ...
3  tiada kata selain subhanallah, ini masjid bagu...
4  setiap kali ke aceh, wajib kesini, masjid ini ...

In [12]:
print("Sebelum:")
print(df["text"].iloc[0])

print("\n" + "="*50 + "\n")

print("Sesudah:")
print(df_casefold["text"].iloc[0])

Sebelum:
Masjid raya Baiturrahman Aceh Dibangun pada masa Kesultanan Aceh (sekitar tahun 1612) oleh Sultan Iskandar Muda. Ada juga versi yang menyebutkan pembangunannya lebih awal lagi.
Simbol Perlawanan: Saat Belanda menyerang Aceh pada tahun 1873, masjid ini sempat dibakar. Namun, karena perlawanan rakyat Aceh yang luar biasa, Belanda terpaksa membangunnya kembali pada tahun 1879 untuk meredam kemarahan masyarakat.
Arsitektur: Mengusung gaya Mughal (India) dengan kubah-kubah hitam yang ikonik. Saat ini, masjid tersebut telah direnovasi menyerupai Masjid Nabawi di Madinah dengan tambahan payung-payung elektrik raksasa di halamannya.
2. Saksi Bisu Tsunami 2004
Inilah momen yang paling menggetarkan dunia, yang berkaitan dengan obrolan kita tentang Kun Fayakun:
Tetap Kokoh: Saat gempa 9,1 SR dan gelombang Tsunami menyapu bersih kota Banda Aceh pada 26 Desember 2004, Masjid Raya Baiturrahman tetap berdiri tegak.
Tempat Perlindungan: Ketika bangunan di sekelilingnya hancur rata dengan tanah, ribuan warga (muslim maupun non-muslim) berlari ke dalam masjid ini dan selamat. Air tsunami masuk ke dalam masjid, namun strukturnya tidak roboh sedikit pun.
Fenomena Spiritual: Foto masjid yang berdiri sendirian di tengah hamparan puing-puing bangunan yang hancur menjadi foto paling ikonik di dunia, membuktikan bahwa jika Allah berkehendak melindungi sesuatu, tidak ada kekuatan alam manapun yang bisa menghancurkannya

==================================================

Sesudah:
masjid raya baiturrahman aceh dibangun pada masa kesultanan aceh (sekitar tahun 1612) oleh sultan iskandar muda. ada juga versi yang menyebutkan pembangunannya lebih awal lagi.
simbol perlawanan: saat belanda menyerang aceh pada tahun 1873, masjid ini sempat dibakar. namun, karena perlawanan rakyat aceh yang luar biasa, belanda terpaksa membangunnya kembali pada tahun 1879 untuk meredam kemarahan masyarakat.
arsitektur: mengusung gaya mughal (india) dengan kubah-kubah hitam yang ikonik. saat ini, masjid tersebut telah direnovasi menyerupai masjid nabawi di madinah dengan tambahan payung-payung elektrik raksasa di halamannya.
2. saksi bisu tsunami 2004
inilah momen yang paling menggetarkan dunia, yang berkaitan dengan obrolan kita tentang kun fayakun:
tetap kokoh: saat gempa 9,1 sr dan gelombang tsunami menyapu bersih kota banda aceh pada 26 desember 2004, masjid raya baiturrahman tetap berdiri tegak.
tempat perlindungan: ketika bangunan di sekelilingnya hancur rata dengan tanah, ribuan warga (muslim maupun non-muslim) berlari ke dalam masjid ini dan selamat. air tsunami masuk ke dalam masjid, namun strukturnya tidak roboh sedikit pun.
fenomena spiritual: foto masjid yang berdiri sendirian di tengah hamparan puing-puing bangunan yang hancur menjadi foto paling ikonik di dunia, membuktikan bahwa jika allah berkehendak melindungi sesuatu, tidak ada kekuatan alam manapun yang bisa menghancurkannya

In [13]:
df_casefold.to_csv(
    "dataset_casefold.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Case folding selesai")

Case folding selesai

Cleaning Text

In [14]:
import re

In [15]:
def clean_text(text):
    text = str(text)

    # hapus URL
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)

    # hapus mention dan hashtag
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)

    # hapus angka
    text = re.sub(r'\d+', '', text)

    # hapus tanda baca dan karakter khusus
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # hapus spasi berlebih
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [16]:
df_clean = df_casefold.copy()

df_clean["text"] = df_clean["text"].apply(clean_text)

df_clean[["text"]].head()

                                                text
0  masjid raya baiturrahman aceh dibangun pada ma...
1  masjid penuh sejarah bagi masyarakat terutama ...
2  mashaallah diijinkan untuk berkunjung kesini s...
3  tiada kata selain subhanallah ini masjid bagus...
4  setiap kali ke aceh wajib kesini masjid ini bu...

In [17]:
print("SEBELUM CLEANING")
print(df_casefold["text"].iloc[0])

print("\n" + "="*60 + "\n")

print("SESUDAH CLEANING")
print(df_clean["text"].iloc[0])

SEBELUM CLEANING
masjid raya baiturrahman aceh dibangun pada masa kesultanan aceh (sekitar tahun 1612) oleh sultan iskandar muda. ada juga versi yang menyebutkan pembangunannya lebih awal lagi.
simbol perlawanan: saat belanda menyerang aceh pada tahun 1873, masjid ini sempat dibakar. namun, karena perlawanan rakyat aceh yang luar biasa, belanda terpaksa membangunnya kembali pada tahun 1879 untuk meredam kemarahan masyarakat.
arsitektur: mengusung gaya mughal (india) dengan kubah-kubah hitam yang ikonik. saat ini, masjid tersebut telah direnovasi menyerupai masjid nabawi di madinah dengan tambahan payung-payung elektrik raksasa di halamannya.
2. saksi bisu tsunami 2004
inilah momen yang paling menggetarkan dunia, yang berkaitan dengan obrolan kita tentang kun fayakun:
tetap kokoh: saat gempa 9,1 sr dan gelombang tsunami menyapu bersih kota banda aceh pada 26 desember 2004, masjid raya baiturrahman tetap berdiri tegak.
tempat perlindungan: ketika bangunan di sekelilingnya hancur rata dengan tanah, ribuan warga (muslim maupun non-muslim) berlari ke dalam masjid ini dan selamat. air tsunami masuk ke dalam masjid, namun strukturnya tidak roboh sedikit pun.
fenomena spiritual: foto masjid yang berdiri sendirian di tengah hamparan puing-puing bangunan yang hancur menjadi foto paling ikonik di dunia, membuktikan bahwa jika allah berkehendak melindungi sesuatu, tidak ada kekuatan alam manapun yang bisa menghancurkannya

============================================================

SESUDAH CLEANING
masjid raya baiturrahman aceh dibangun pada masa kesultanan aceh sekitar tahun oleh sultan iskandar muda ada juga versi yang menyebutkan pembangunannya lebih awal lagi simbol perlawanan saat belanda menyerang aceh pada tahun masjid ini sempat dibakar namun karena perlawanan rakyat aceh yang luar biasa belanda terpaksa membangunnya kembali pada tahun untuk meredam kemarahan masyarakat arsitektur mengusung gaya mughal india dengan kubah kubah hitam yang ikonik saat ini masjid tersebut telah direnovasi menyerupai masjid nabawi di madinah dengan tambahan payung payung elektrik raksasa di halamannya saksi bisu tsunami inilah momen yang paling menggetarkan dunia yang berkaitan dengan obrolan kita tentang kun fayakun tetap kokoh saat gempa sr dan gelombang tsunami menyapu bersih kota banda aceh pada desember masjid raya baiturrahman tetap berdiri tegak tempat perlindungan ketika bangunan di sekelilingnya hancur rata dengan tanah ribuan warga muslim maupun non muslim berlari ke dalam masjid ini dan selamat air tsunami masuk ke dalam masjid namun strukturnya tidak roboh sedikit pun fenomena spiritual foto masjid yang berdiri sendirian di tengah hamparan puing puing bangunan yang hancur menjadi foto paling ikonik di dunia membuktikan bahwa jika allah berkehendak melindungi sesuatu tidak ada kekuatan alam manapun yang bisa menghancurkannya

In [18]:
print("Sebelum:", len(df_clean))

df_clean = df_clean[df_clean["text"].str.strip() != ""]

print("Sesudah:", len(df_clean))

Sebelum: 2736
Sesudah: 2582

In [19]:
df_clean.to_csv(
    "dataset_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Cleaning selesai")

Cleaning selesai

Tokenizing

In [20]:
df_token = df_clean.copy()

df_token["tokens"] = df_token["text"].apply(lambda x: x.split())

df_token[["text", "tokens"]].head()

,text,tokens
0,masjid raya baiturrahman aceh dibangun pada ma...,"[masjid, raya, baiturrahman, aceh, dibangun, p..."
1,masjid penuh sejarah bagi masyarakat terutama ...,"[masjid, penuh, sejarah, bagi, masyarakat, ter..."
2,mashaallah diijinkan untuk berkunjung kesini s...,"[mashaallah, diijinkan, untuk, berkunjung, kes..."
3,tiada kata selain subhanallah ini masjid bagus...,"[tiada, kata, selain, subhanallah, ini, masjid..."
4,setiap kali ke aceh wajib kesini masjid ini bu...,"[setiap, kali, ke, aceh, wajib, kesini, masjid..."

In [21]:
print(df_token["text"].iloc[0])

print("\n")

print(df_token["tokens"].iloc[0])

masjid raya baiturrahman aceh dibangun pada masa kesultanan aceh sekitar tahun oleh sultan iskandar muda ada juga versi yang menyebutkan pembangunannya lebih awal lagi simbol perlawanan saat belanda menyerang aceh pada tahun masjid ini sempat dibakar namun karena perlawanan rakyat aceh yang luar biasa belanda terpaksa membangunnya kembali pada tahun untuk meredam kemarahan masyarakat arsitektur mengusung gaya mughal india dengan kubah kubah hitam yang ikonik saat ini masjid tersebut telah direnovasi menyerupai masjid nabawi di madinah dengan tambahan payung payung elektrik raksasa di halamannya saksi bisu tsunami inilah momen yang paling menggetarkan dunia yang berkaitan dengan obrolan kita tentang kun fayakun tetap kokoh saat gempa sr dan gelombang tsunami menyapu bersih kota banda aceh pada desember masjid raya baiturrahman tetap berdiri tegak tempat perlindungan ketika bangunan di sekelilingnya hancur rata dengan tanah ribuan warga muslim maupun non muslim berlari ke dalam masjid ini dan selamat air tsunami masuk ke dalam masjid namun strukturnya tidak roboh sedikit pun fenomena spiritual foto masjid yang berdiri sendirian di tengah hamparan puing puing bangunan yang hancur menjadi foto paling ikonik di dunia membuktikan bahwa jika allah berkehendak melindungi sesuatu tidak ada kekuatan alam manapun yang bisa menghancurkannya


['masjid', 'raya', 'baiturrahman', 'aceh', 'dibangun', 'pada', 'masa', 'kesultanan', 'aceh', 'sekitar', 'tahun', 'oleh', 'sultan', 'iskandar', 'muda', 'ada', 'juga', 'versi', 'yang', 'menyebutkan', 'pembangunannya', 'lebih', 'awal', 'lagi', 'simbol', 'perlawanan', 'saat', 'belanda', 'menyerang', 'aceh', 'pada', 'tahun', 'masjid', 'ini', 'sempat', 'dibakar', 'namun', 'karena', 'perlawanan', 'rakyat', 'aceh', 'yang', 'luar', 'biasa', 'belanda', 'terpaksa', 'membangunnya', 'kembali', 'pada', 'tahun', 'untuk', 'meredam', 'kemarahan', 'masyarakat', 'arsitektur', 'mengusung', 'gaya', 'mughal', 'india', 'dengan', 'kubah', 'kubah', 'hitam', 'yang', 'ikonik', 'saat', 'ini', 'masjid', 'tersebut', 'telah', 'direnovasi', 'menyerupai', 'masjid', 'nabawi', 'di', 'madinah', 'dengan', 'tambahan', 'payung', 'payung', 'elektrik', 'raksasa', 'di', 'halamannya', 'saksi', 'bisu', 'tsunami', 'inilah', 'momen', 'yang', 'paling', 'menggetarkan', 'dunia', 'yang', 'berkaitan', 'dengan', 'obrolan', 'kita', 'tentang', 'kun', 'fayakun', 'tetap', 'kokoh', 'saat', 'gempa', 'sr', 'dan', 'gelombang', 'tsunami', 'menyapu', 'bersih', 'kota', 'banda', 'aceh', 'pada', 'desember', 'masjid', 'raya', 'baiturrahman', 'tetap', 'berdiri', 'tegak', 'tempat', 'perlindungan', 'ketika', 'bangunan', 'di', 'sekelilingnya', 'hancur', 'rata', 'dengan', 'tanah', 'ribuan', 'warga', 'muslim', 'maupun', 'non', 'muslim', 'berlari', 'ke', 'dalam', 'masjid', 'ini', 'dan', 'selamat', 'air', 'tsunami', 'masuk', 'ke', 'dalam', 'masjid', 'namun', 'strukturnya', 'tidak', 'roboh', 'sedikit', 'pun', 'fenomena', 'spiritual', 'foto', 'masjid', 'yang', 'berdiri', 'sendirian', 'di', 'tengah', 'hamparan', 'puing', 'puing', 'bangunan', 'yang', 'hancur', 'menjadi', 'foto', 'paling', 'ikonik', 'di', 'dunia', 'membuktikan', 'bahwa', 'jika', 'allah', 'berkehendak', 'melindungi', 'sesuatu', 'tidak', 'ada', 'kekuatan', 'alam', 'manapun', 'yang', 'bisa', 'menghancurkannya']

In [22]:
df_token.to_csv(
    "dataset_tokenizing.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Tokenizing selesai")

Tokenizing selesai

Stopword Removal

In [23]:
!pip install Sastrawi

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 1.4 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [24]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

In [25]:
factory = StopWordRemoverFactory()

stopwords = set(factory.get_stop_words())

print("Jumlah stopword :", len(stopwords))

Jumlah stopword : 123

In [26]:
df_stopword = df_token.copy()

df_stopword["tokens"] = df_stopword["tokens"].apply(
    lambda words: [word for word in words if word not in stopwords]
)

df_stopword[["tokens"]].head()

                                              tokens
0  [masjid, raya, baiturrahman, aceh, dibangun, m...
1  [masjid, penuh, sejarah, masyarakat, terutama,...
2  [mashaallah, diijinkan, berkunjung, kesini, sa...
3  [tiada, kata, subhanallah, masjid, bagus, mega...
4  [kali, aceh, wajib, kesini, masjid, bukan, ind...

In [27]:
print("SEBELUM")
print(df_token["tokens"].iloc[0])

print("\n" + "="*60 + "\n")

print("SESUDAH")
print(df_stopword["tokens"].iloc[0])

SEBELUM
['masjid', 'raya', 'baiturrahman', 'aceh', 'dibangun', 'pada', 'masa', 'kesultanan', 'aceh', 'sekitar', 'tahun', 'oleh', 'sultan', 'iskandar', 'muda', 'ada', 'juga', 'versi', 'yang', 'menyebutkan', 'pembangunannya', 'lebih', 'awal', 'lagi', 'simbol', 'perlawanan', 'saat', 'belanda', 'menyerang', 'aceh', 'pada', 'tahun', 'masjid', 'ini', 'sempat', 'dibakar', 'namun', 'karena', 'perlawanan', 'rakyat', 'aceh', 'yang', 'luar', 'biasa', 'belanda', 'terpaksa', 'membangunnya', 'kembali', 'pada', 'tahun', 'untuk', 'meredam', 'kemarahan', 'masyarakat', 'arsitektur', 'mengusung', 'gaya', 'mughal', 'india', 'dengan', 'kubah', 'kubah', 'hitam', 'yang', 'ikonik', 'saat', 'ini', 'masjid', 'tersebut', 'telah', 'direnovasi', 'menyerupai', 'masjid', 'nabawi', 'di', 'madinah', 'dengan', 'tambahan', 'payung', 'payung', 'elektrik', 'raksasa', 'di', 'halamannya', 'saksi', 'bisu', 'tsunami', 'inilah', 'momen', 'yang', 'paling', 'menggetarkan', 'dunia', 'yang', 'berkaitan', 'dengan', 'obrolan', 'kita', 'tentang', 'kun', 'fayakun', 'tetap', 'kokoh', 'saat', 'gempa', 'sr', 'dan', 'gelombang', 'tsunami', 'menyapu', 'bersih', 'kota', 'banda', 'aceh', 'pada', 'desember', 'masjid', 'raya', 'baiturrahman', 'tetap', 'berdiri', 'tegak', 'tempat', 'perlindungan', 'ketika', 'bangunan', 'di', 'sekelilingnya', 'hancur', 'rata', 'dengan', 'tanah', 'ribuan', 'warga', 'muslim', 'maupun', 'non', 'muslim', 'berlari', 'ke', 'dalam', 'masjid', 'ini', 'dan', 'selamat', 'air', 'tsunami', 'masuk', 'ke', 'dalam', 'masjid', 'namun', 'strukturnya', 'tidak', 'roboh', 'sedikit', 'pun', 'fenomena', 'spiritual', 'foto', 'masjid', 'yang', 'berdiri', 'sendirian', 'di', 'tengah', 'hamparan', 'puing', 'puing', 'bangunan', 'yang', 'hancur', 'menjadi', 'foto', 'paling', 'ikonik', 'di', 'dunia', 'membuktikan', 'bahwa', 'jika', 'allah', 'berkehendak', 'melindungi', 'sesuatu', 'tidak', 'ada', 'kekuatan', 'alam', 'manapun', 'yang', 'bisa', 'menghancurkannya']

============================================================

SESUDAH
['masjid', 'raya', 'baiturrahman', 'aceh', 'dibangun', 'masa', 'kesultanan', 'aceh', 'tahun', 'sultan', 'iskandar', 'muda', 'versi', 'menyebutkan', 'pembangunannya', 'lebih', 'awal', 'simbol', 'perlawanan', 'belanda', 'menyerang', 'aceh', 'tahun', 'masjid', 'sempat', 'dibakar', 'perlawanan', 'rakyat', 'aceh', 'luar', 'biasa', 'belanda', 'terpaksa', 'membangunnya', 'tahun', 'meredam', 'kemarahan', 'masyarakat', 'arsitektur', 'mengusung', 'gaya', 'mughal', 'india', 'kubah', 'kubah', 'hitam', 'ikonik', 'masjid', 'tersebut', 'direnovasi', 'menyerupai', 'masjid', 'nabawi', 'madinah', 'tambahan', 'payung', 'payung', 'elektrik', 'raksasa', 'halamannya', 'saksi', 'bisu', 'tsunami', 'inilah', 'momen', 'paling', 'menggetarkan', 'dunia', 'berkaitan', 'obrolan', 'kun', 'fayakun', 'tetap', 'kokoh', 'gempa', 'sr', 'gelombang', 'tsunami', 'menyapu', 'bersih', 'kota', 'banda', 'aceh', 'desember', 'masjid', 'raya', 'baiturrahman', 'tetap', 'berdiri', 'tegak', 'tempat', 'perlindungan', 'bangunan', 'sekelilingnya', 'hancur', 'rata', 'tanah', 'ribuan', 'warga', 'muslim', 'maupun', 'non', 'muslim', 'berlari', 'masjid', 'selamat', 'air', 'tsunami', 'masuk', 'masjid', 'strukturnya', 'roboh', 'sedikit', 'fenomena', 'spiritual', 'foto', 'masjid', 'berdiri', 'sendirian', 'tengah', 'hamparan', 'puing', 'puing', 'bangunan', 'hancur', 'menjadi', 'foto', 'paling', 'ikonik', 'dunia', 'membuktikan', 'allah', 'berkehendak', 'melindungi', 'kekuatan', 'alam', 'manapun', 'menghancurkannya']

In [28]:
df_stopword.to_csv(
    "dataset_stopword.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Stopword removal selesai")

Stopword removal selesai

Stemming

In [29]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [30]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [31]:
df_stemming = df_stopword.copy()

df_stemming["tokens"] = df_stemming["tokens"].apply(
    lambda words: [stemmer.stem(word) for word in words]
)

df_stemming[["tokens"]].head()

                                              tokens
0  [masjid, raya, baiturrahman, aceh, bangun, mas...
1  [masjid, penuh, sejarah, masyarakat, utama, ba...
2  [mashaallah, diijinkan, kunjung, kesini, saksi...
3  [tiada, kata, subhanallah, masjid, bagus, mega...
4  [kali, aceh, wajib, kesini, masjid, bukan, ind...

In [32]:
print("SEBELUM")
print(df_stopword["tokens"].iloc[0])

print("\n" + "="*60 + "\n")

print("SESUDAH")
print(df_stemming["tokens"].iloc[0])

SEBELUM
['masjid', 'raya', 'baiturrahman', 'aceh', 'dibangun', 'masa', 'kesultanan', 'aceh', 'tahun', 'sultan', 'iskandar', 'muda', 'versi', 'menyebutkan', 'pembangunannya', 'lebih', 'awal', 'simbol', 'perlawanan', 'belanda', 'menyerang', 'aceh', 'tahun', 'masjid', 'sempat', 'dibakar', 'perlawanan', 'rakyat', 'aceh', 'luar', 'biasa', 'belanda', 'terpaksa', 'membangunnya', 'tahun', 'meredam', 'kemarahan', 'masyarakat', 'arsitektur', 'mengusung', 'gaya', 'mughal', 'india', 'kubah', 'kubah', 'hitam', 'ikonik', 'masjid', 'tersebut', 'direnovasi', 'menyerupai', 'masjid', 'nabawi', 'madinah', 'tambahan', 'payung', 'payung', 'elektrik', 'raksasa', 'halamannya', 'saksi', 'bisu', 'tsunami', 'inilah', 'momen', 'paling', 'menggetarkan', 'dunia', 'berkaitan', 'obrolan', 'kun', 'fayakun', 'tetap', 'kokoh', 'gempa', 'sr', 'gelombang', 'tsunami', 'menyapu', 'bersih', 'kota', 'banda', 'aceh', 'desember', 'masjid', 'raya', 'baiturrahman', 'tetap', 'berdiri', 'tegak', 'tempat', 'perlindungan', 'bangunan', 'sekelilingnya', 'hancur', 'rata', 'tanah', 'ribuan', 'warga', 'muslim', 'maupun', 'non', 'muslim', 'berlari', 'masjid', 'selamat', 'air', 'tsunami', 'masuk', 'masjid', 'strukturnya', 'roboh', 'sedikit', 'fenomena', 'spiritual', 'foto', 'masjid', 'berdiri', 'sendirian', 'tengah', 'hamparan', 'puing', 'puing', 'bangunan', 'hancur', 'menjadi', 'foto', 'paling', 'ikonik', 'dunia', 'membuktikan', 'allah', 'berkehendak', 'melindungi', 'kekuatan', 'alam', 'manapun', 'menghancurkannya']

============================================================

SESUDAH
['masjid', 'raya', 'baiturrahman', 'aceh', 'bangun', 'masa', 'sultan', 'aceh', 'tahun', 'sultan', 'iskandar', 'muda', 'versi', 'sebut', 'bangun', 'lebih', 'awal', 'simbol', 'lawan', 'belanda', 'serang', 'aceh', 'tahun', 'masjid', 'sempat', 'bakar', 'lawan', 'rakyat', 'aceh', 'luar', 'biasa', 'belanda', 'paksa', 'bangun', 'tahun', 'redam', 'marah', 'masyarakat', 'arsitektur', 'usung', 'gaya', 'mughal', 'india', 'kubah', 'kubah', 'hitam', 'ikonik', 'masjid', 'sebut', 'renovasi', 'rupa', 'masjid', 'nabawi', 'madinah', 'tambah', 'payung', 'payung', 'elektrik', 'raksasa', 'halaman', 'saksi', 'bisu', 'tsunami', 'ini', 'momen', 'paling', 'getar', 'dunia', 'kait', 'obrol', 'kun', 'fayakun', 'tetap', 'kokoh', 'gempa', 'sr', 'gelombang', 'tsunami', 'sapu', 'bersih', 'kota', 'banda', 'aceh', 'desember', 'masjid', 'raya', 'baiturrahman', 'tetap', 'diri', 'tegak', 'tempat', 'lindung', 'bangun', 'keliling', 'hancur', 'rata', 'tanah', 'ribu', 'warga', 'muslim', 'maupun', 'non', 'muslim', 'lari', 'masjid', 'selamat', 'air', 'tsunami', 'masuk', 'masjid', 'struktur', 'roboh', 'sedikit', 'fenomena', 'spiritual', 'foto', 'masjid', 'diri', 'sendiri', 'tengah', 'hampar', 'puing', 'puing', 'bangun', 'hancur', 'jadi', 'foto', 'paling', 'ikonik', 'dunia', 'bukti', 'allah', 'hendak', 'lindung', 'kuat', 'alam', 'mana', 'hancur']

In [33]:
df_stemming["text_preprocessed"] = df_stemming["tokens"].apply(
    lambda x: " ".join(x)
)

df_stemming[
    ["text","text_preprocessed"]
].head()

,text,text_preprocessed
0,masjid raya baiturrahman aceh dibangun pada ma...,masjid raya baiturrahman aceh bangun masa sult...
1,masjid penuh sejarah bagi masyarakat terutama ...,masjid penuh sejarah masyarakat utama banda ac...
2,mashaallah diijinkan untuk berkunjung kesini s...,mashaallah diijinkan kunjung kesini saksi bisu...
3,tiada kata selain subhanallah ini masjid bagus...,tiada kata subhanallah masjid bagus megah bang...
4,setiap kali ke aceh wajib kesini masjid ini bu...,kali aceh wajib kesini masjid bukan indah mega...

In [34]:
from google.colab import drive
drive.mount('/content/drive')

df_stemming.to_csv(
    "/content/drive/MyDrive/SEMESTER 6/DATASET/dataset_preprocessing_final.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Preprocessing selesai dan tersimpan")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Preprocessing selesai dan tersimpan

In [35]:
import os

os.path.exists(
    "/content/drive/MyDrive/SEMESTER 6/DATASET/dataset_preprocessing_final.csv"
)

True